"""Workflow graph definition: tasks, nodes, edges, and the workflow itself.

The graph is *data*. Validation, scheduling, and execution live elsewhere
(:mod:`orchestration.workflow`), so a workflow can be authored in YAML, produced
by the supervisor at runtime, persisted to JSONB, and round-tripped through a
checkpoint without any of those paths needing to construct behaviour objects.

Both static workflows and supervisor-generated plans compile to this same
structure, which is the reason checkpoint/resume, cancellation, budgets, and
approvals behave identically for each.
"""

from __future__ import annotations

from typing import Literal, Self

from pydantic import Field, model_validator

from orchestration.domain.base import (
    BoundedText,
    DomainModel,
    FrozenModel,
    JsonDict,
    Score,
    Slug,
    TimestampedModel,
    id_factory,
)
from orchestration.domain.budget import Budget
from orchestration.domain.enums import JoinPolicy, NodeKind
from orchestration.domain.retry import DEFAULT_RETRY_POLICY, RetryPolicy


class Task(TimestampedModel):
    """A unit of work submitted by a user or generated by the supervisor."""

    id: str = Field(default_factory=id_factory("task"))
    description: BoundedText = Field(min_length=1)
    #: Structured inputs (file paths, parameters, prior findings).
    inputs: JsonDict = Field(default_factory=dict)
    #: What "done" looks like, used by the critic and finalizer.
    success_criteria: tuple[str, ...] = ()
    #: Optional parent for supervisor-generated subtasks.
    parent_task_id: str | None = None
    priority: int = Field(default=0, ge=-100, le=100)
    metadata: JsonDict = Field(default_factory=dict)


class Condition(FrozenModel):
    """A single predicate evaluated against execution state.

    Conditions are a tiny closed expression language rather than Python ``eval``:
    a workflow definition is untrusted input (it can arrive over the API or from
    an LLM), so it must not be able to execute arbitrary code.

    ``path`` is a dotted lookup into the evaluation context, e.g.
    ``"outputs.research.confidence"``.
    """

    path: str = Field(min_length=1, max_length=256)
    operator: Literal[
        "eq",
        "ne",
        "lt",
        "lte",
        "gt",
        "gte",
        "in",
        "not_in",
        "contains",
        "exists",
        "not_exists",
        "truthy",
        "falsy",
    ]
    value: JsonDict | str | float | int | bool | list[str] | list[float] | None = None

    def describe(self) -> str:
        return f"{self.path} {self.operator} {self.value!r}"


class NodeCondition(FrozenModel):
    """A named group of predicates gating an edge or a branch outcome."""

    conditions: tuple[Condition, ...] = ()
    mode: Literal["all", "any"] = "all"

    @property
    def is_empty(self) -> bool:
        return not self.conditions

    def describe(self) -> str:
        if self.is_empty:
            return "always"
        joiner = " AND " if self.mode == "all" else " OR "
        return joiner.join(c.describe() for c in self.conditions)


class WorkflowNode(FrozenModel):
    """One vertex in the execution graph.

    Behaviour is selected by :attr:`kind` rather than by subclassing, so the node
    survives a JSONB round-trip without polymorphic deserialisation -- which is a
    hard requirement for checkpoint/resume.
    """

    id: Slug
    kind: NodeKind
    name: str = Field(default="", max_length=128)
    description: str = Field(default="", max_length=1_000)

    # -- kind-specific targets --
    #: Required when kind is AGENT.
    agent_id: Slug | None = None
    #: Required when kind is TOOL.
    tool: Slug | None = None
    tool_arguments: JsonDict = Field(default_factory=dict)

    # -- join semantics (kind == JOIN) --
    join_policy: JoinPolicy = JoinPolicy.ALL
    quorum: int | None = Field(default=None, ge=1)

    # -- approval semantics (kind == APPROVAL) --
    approval_reason: str = Field(default="", max_length=1_000)

    # -- execution controls --
    #: Prompt/instruction template for agent nodes; ``{placeholders}`` are filled
    #: from execution variables and upstream outputs.
    input_template: BoundedText = ""
    timeout_seconds: float | None = Field(default=None, gt=0, le=3_600.0)
    retry_policy: RetryPolicy = DEFAULT_RETRY_POLICY
    #: When true, a failure here does not fail the execution; downstream nodes
    #: see the node as complete-but-failed and may proceed on partial results.
    optional: bool = False
    #: Node to jump to when this node exhausts its retries.
    on_failure_node: Slug | None = None
    #: Store the node output in execution variables under this key.
    output_key: str | None = Field(default=None, max_length=128)
    #: Minimum acceptable confidence; below it the node is treated as
    #: low-confidence and the supervisor may order follow-up work.
    confidence_floor: Score | None = None
    metadata: JsonDict = Field(default_factory=dict)

    @model_validator(mode="after")
    def _validate_kind_requirements(self) -> Self:
        """Each node kind carries the fields its executor needs.

        Checked here so an ill-formed node -- including one produced by a
        replanning LLM -- is rejected at construction rather than failing
        halfway through execution with an attribute error.
        """
        if self.kind is NodeKind.AGENT and not self.agent_id:
            raise ValueError(f"node {self.id!r} of kind 'agent' requires agent_id")
        if self.kind is NodeKind.TOOL and not self.tool:
            raise ValueError(f"node {self.id!r} of kind 'tool' requires tool")
        if self.kind is NodeKind.JOIN and self.join_policy is JoinPolicy.QUORUM and not self.quorum:
            raise ValueError(f"join node {self.id!r} with policy 'quorum' requires quorum")
        if self.kind is not NodeKind.JOIN and self.quorum is not None:
            raise ValueError(f"node {self.id!r} sets quorum but is not a join node")
        if self.kind is NodeKind.AGENT and self.tool:
            raise ValueError(f"node {self.id!r} cannot set both agent_id and tool")
        return self

    @property
    def effective_name(self) -> str:
        return self.name or self.id


class WorkflowEdge(FrozenModel):
    """A directed dependency between two nodes.

    An edge may carry a condition, which is how conditional routing is expressed:
    the edge activates only when its predicates hold against execution state.
    """

    id: str = Field(default_factory=id_factory("edge"))
    source: Slug
    target: Slug
    condition: NodeCondition | None = None
    #: Human-readable label for diagrams and traces.
    label: str = Field(default="", max_length=128)

    @property
    def is_conditional(self) -> bool:
        return self.condition is not None and not self.condition.is_empty

    def describe(self) -> str:
        arrow = f"--{self.label}-->" if self.label else "-->"
        if self.is_conditional:
            assert self.condition is not None
            return f"{self.source} {arrow} {self.target} [{self.condition.describe()}]"
        return f"{self.source} {arrow} {self.target}"


class Workflow(TimestampedModel):
    """A complete workflow definition.

    Structural validation (cycles, unknown references, unreachable nodes) is
    performed by :class:`orchestration.workflow.graph.WorkflowGraph`, not here:
    Pydantic validators guard *local* invariants, while graph properties need the
    whole-graph view and produce a collected list of problems rather than the
    first error.
    """

    id: str = Field(default_factory=id_factory("workflow"))
    name: str = Field(min_length=1, max_length=128)
    description: str = Field(default="", max_length=2_000)
    version: str = Field(default="1.0.0", max_length=32)
    nodes: tuple[WorkflowNode, ...] = Field(min_length=1)
    edges: tuple[WorkflowEdge, ...] = ()
    #: Entry points. When omitted, nodes with no inbound edges are used.
    entry_nodes: tuple[Slug, ...] = ()
    budget: Budget | None = None
    #: Initial execution variables available to templates and conditions.
    variables: JsonDict = Field(default_factory=dict)
    #: True when produced by the supervisor rather than authored statically.
    dynamic: bool = False
    tags: frozenset[str] = Field(default_factory=frozenset)
    metadata: JsonDict = Field(default_factory=dict)

    @model_validator(mode="after")
    def _unique_node_ids(self) -> Self:
        ids = [n.id for n in self.nodes]
        duplicates = sorted({i for i in ids if ids.count(i) > 1})
        if duplicates:
            raise ValueError(f"workflow {self.name!r} has duplicate node ids: {duplicates}")
        return self

    @model_validator(mode="after")
    def _edges_reference_known_nodes(self) -> Self:
        known = {n.id for n in self.nodes}
        problems = [
            f"edge {e.source}->{e.target} references unknown node "
            f"{e.source if e.source not in known else e.target!r}"
            for e in self.edges
            if e.source not in known or e.target not in known
        ]
        if problems:
            raise ValueError("; ".join(problems))
        return self

    @model_validator(mode="after")
    def _entry_nodes_exist(self) -> Self:
        known = {n.id for n in self.nodes}
        unknown = sorted(set(self.entry_nodes) - known)
        if unknown:
            raise ValueError(f"workflow {self.name!r} declares unknown entry nodes: {unknown}")
        return self

    # -- accessors ---------------------------------------------------------

    @property
    def node_map(self) -> dict[str, WorkflowNode]:
        return {n.id: n for n in self.nodes}

    def node(self, node_id: str) -> WorkflowNode | None:
        return self.node_map.get(node_id)

    @property
    def resolved_entry_nodes(self) -> tuple[str, ...]:
        """Declared entry points, or all nodes with no inbound edges."""
        if self.entry_nodes:
            return self.entry_nodes
        targets = {e.target for e in self.edges}
        return tuple(n.id for n in self.nodes if n.id not in targets)

    def successors(self, node_id: str) -> tuple[WorkflowEdge, ...]:
        return tuple(e for e in self.edges if e.source == node_id)

    def predecessors(self, node_id: str) -> tuple[WorkflowEdge, ...]:
        return tuple(e for e in self.edges if e.target == node_id)

    @property
    def agent_ids(self) -> frozenset[str]:
        return frozenset(n.agent_id for n in self.nodes if n.agent_id)

    @property
    def tool_names(self) -> frozenset[str]:
        return frozenset(n.tool for n in self.nodes if n.tool)

    def extended_with(
        self,
        nodes: tuple[WorkflowNode, ...],
        edges: tuple[WorkflowEdge, ...],
    ) -> Workflow:
        """Return a copy with additional nodes and edges appended.

        This is the mechanism behind dynamic replanning: the supervisor produces
        a subgraph, it is validated, and the *result* replaces the live workflow.
        Returning a new object rather than mutating keeps the pre-replan graph
        intact in the checkpoint history.
        """
        return type(self).model_validate(
            {
                **self.model_dump(),
                "nodes": tuple(self.nodes) + tuple(nodes),
                "edges": tuple(self.edges) + tuple(edges),
                "dynamic": True,
            }
        )

    def to_mermaid(self) -> str:
        """Render the graph as a Mermaid flowchart.

        Used by the CLI and the docs so a diagram never drifts from the actual
        definition -- it is generated from the same data the engine executes.
        """
        shapes: dict[NodeKind, tuple[str, str]] = {
            NodeKind.AGENT: ("[", "]"),
            NodeKind.TOOL: ("[/", "/]"),
            NodeKind.SUPERVISOR: ("{{", "}}"),
            NodeKind.BRANCH: ("{", "}"),
            NodeKind.JOIN: ("[(", ")]"),
            NodeKind.APPROVAL: (">", "]"),
            NodeKind.TERMINAL: ("([", "])"),
        }
        lines = ["flowchart TD"]
        for node in self.nodes:
            open_s, close_s = shapes.get(node.kind, ("[", "]"))
            label = node.effective_name.replace('"', "'")
            suffix = (
                f"<br/><i>{node.agent_id or node.tool}</i>" if (node.agent_id or node.tool) else ""
            )
            lines.append(f'    {node.id}{open_s}"{label}{suffix}"{close_s}')
        for edge in self.edges:
            if edge.is_conditional:
                assert edge.condition is not None
                label = edge.label or edge.condition.describe()
                lines.append(f'    {edge.source} -->|"{label}"| {edge.target}')
            elif edge.label:
                lines.append(f'    {edge.source} -->|"{edge.label}"| {edge.target}')
            else:
                lines.append(f"    {edge.source} --> {edge.target}")
        return "\n".join(lines)


class DynamicPlan(DomainModel):
    """A supervisor-produced subgraph awaiting validation.

    Kept as its own type so that "a plan the LLM proposed" and "a workflow the
    engine will run" are different things in the type system. A plan becomes
    executable only after graph and policy validation convert it into a
    :class:`Workflow`.
    """

    nodes: tuple[WorkflowNode, ...] = Field(min_length=1)
    edges: tuple[WorkflowEdge, ...] = ()
    reason: str = Field(default="", max_length=2_000)
    #: Existing node ids the new subgraph attaches to.
    attach_after: tuple[Slug, ...] = ()

    @model_validator(mode="after")
    def _internal_edges_resolve(self) -> Self:
        """Edges must reference either a new node or a declared attach point."""
        new_ids = {n.id for n in self.nodes}
        allowed = new_ids | set(self.attach_after)
        problems = [
            f"plan edge {e.source}->{e.target} references node outside the plan"
            for e in self.edges
            if e.source not in allowed or e.target not in allowed
        ]
        if problems:
            raise ValueError("; ".join(problems))
        return self
