"""baseline schema

Revision ID: 9ecf4d743017
Revises: 
Create Date: 2026-08-27 11:10:28.241327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '9ecf4d743017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before evidence_chunks.embedding (a vector column) can
    # be created. Idempotent, so this migration is safe to run against a
    # database that already has the extension installed manually.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('ix_agents_definition', 'agents', ['definition'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_agents_enabled'), 'agents', ['enabled'], unique=False)
    op.create_index(op.f('ix_agents_kind'), 'agents', ['kind'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('provider_note', sa.Text(), nullable=False),
    sa.Column('scenario_count', sa.Integer(), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_runs'))
    )
    op.create_index(op.f('ix_benchmark_runs_git_sha'), 'benchmark_runs', ['git_sha'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('idempotency_key', name='uq_executions_idempotency_key')
    )
    op.create_index(op.f('ix_executions_created_at'), 'executions', ['created_at'], unique=False)
    op.create_index('ix_executions_resumable', 'executions', ['status', 'updated_at'], unique=False, postgresql_where=None)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_executions_trace_id'), 'executions', ['trace_id'], unique=False)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions', ['workflow_id'], unique=False)
    op.create_table('tools',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_tools'))
    )
    op.create_index(op.f('ix_tools_risk'), 'tools', ['risk'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('dynamic', sa.Boolean(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows')),
    sa.UniqueConstraint('name', 'version', name='uq_workflows_name_version')
    )
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_table('agent_invocations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_key', sa.String(length=96), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_agent_invocations_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_invocations'))
    )
    op.create_index(op.f('ix_agent_invocations_agent_id'), 'agent_invocations', ['agent_id'], unique=False)
    op.create_index('ix_agent_invocations_exec_node', 'agent_invocations', ['execution_id', 'node_id'], unique=False)
    op.create_index(op.f('ix_agent_invocations_execution_id'), 'agent_invocations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_invocations_model_key'), 'agent_invocations', ['model_key'], unique=False)
    op.create_index(op.f('ix_agent_invocations_status'), 'agent_invocations', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('modified_parameters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_approvals_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_execution_id'), 'approvals', ['execution_id'], unique=False)
    op.create_index(op.f('ix_approvals_expires_at'), 'approvals', ['expires_at'], unique=False)
    op.create_index('ix_approvals_pending', 'approvals', ['execution_id', 'status'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('workflow_snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_checkpoints_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkpoints')),
    sa.UniqueConstraint('execution_id', 'sequence', name='uq_checkpoints_execution_id')
    )
    op.create_index(op.f('ix_checkpoints_execution_id'), 'checkpoints', ['execution_id'], unique=False)
    op.create_index('ix_checkpoints_execution_sequence', 'checkpoints', ['execution_id', 'sequence'], unique=False)
    op.create_index('ix_checkpoints_hash', 'checkpoints', ['execution_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_checkpoints_reason'), 'checkpoints', ['reason'], unique=False)
    op.create_table('evidence_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_evidence_chunks_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_chunks')),
    sa.UniqueConstraint('content_hash', 'source', name='uq_evidence_chunks_content_hash')
    )
    op.create_index(op.f('ix_evidence_chunks_content_hash'), 'evidence_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_chunks_execution_id'), 'evidence_chunks', ['execution_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_events_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events')),
    sa.UniqueConstraint('execution_id', 'sequence', name='uq_execution_events_execution_id')
    )
    op.create_index(op.f('ix_execution_events_agent_id'), 'execution_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_execution_events_execution_id'), 'execution_events', ['execution_id'], unique=False)
    op.create_index('ix_execution_events_execution_sequence', 'execution_events', ['execution_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_execution_events_node_id'), 'execution_events', ['node_id'], unique=False)
    op.create_index('ix_execution_events_payload', 'execution_events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_execution_events_severity'), 'execution_events', ['severity'], unique=False)
    op.create_index(op.f('ix_execution_events_trace_id'), 'execution_events', ['trace_id'], unique=False)
    op.create_index(op.f('ix_execution_events_type'), 'execution_events', ['type'], unique=False)
    op.create_table('execution_states',
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('workflow_snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 0', name=op.f('ck_execution_states_version_non_negative')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_states_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('pk_execution_states'))
    )
    op.create_index('ix_execution_states_state', 'execution_states', ['state'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_execution_states_status'), 'execution_states', ['status'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_effect', sa.String(length=24), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_tool_invocations_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_invocations')),
    sa.UniqueConstraint('idempotency_key', name='uq_tool_invocations_idempotency_key')
    )
    op.create_index(op.f('ix_tool_invocations_agent_id'), 'tool_invocations', ['agent_id'], unique=False)
    op.create_index('ix_tool_invocations_exec_tool', 'tool_invocations', ['execution_id', 'tool'], unique=False)
    op.create_index(op.f('ix_tool_invocations_execution_id'), 'tool_invocations', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_status'), 'tool_invocations', ['status'], unique=False)
    op.create_index(op.f('ix_tool_invocations_tool'), 'tool_invocations', ['tool'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('edge_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('conditional', sa.Boolean(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_edges_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_edges')),
    sa.UniqueConstraint('workflow_id', 'edge_id', name='uq_workflow_edges_workflow_id')
    )
    op.create_index('ix_workflow_edges_source_target', 'workflow_edges', ['workflow_id', 'source', 'target'], unique=False)
    op.create_index(op.f('ix_workflow_edges_workflow_id'), 'workflow_edges', ['workflow_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_nodes_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_nodes')),
    sa.UniqueConstraint('workflow_id', 'node_id', name='uq_workflow_nodes_workflow_id')
    )
    op.create_index(op.f('ix_workflow_nodes_agent_id'), 'workflow_nodes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_kind'), 'workflow_nodes', ['kind'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_tool'), 'workflow_nodes', ['tool'], unique=False)
    op.create_index(op.f('ix_workflow_nodes_workflow_id'), 'workflow_nodes', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Deliberately does not DROP EXTENSION vector: another schema or a manual
    install may depend on it, and removing an extension is a heavier, more
    surprising operation than a reference implementation should perform as a
    side effect of rolling back its own tables.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_nodes_workflow_id'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_tool'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_kind'), table_name='workflow_nodes')
    op.drop_index(op.f('ix_workflow_nodes_agent_id'), table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index(op.f('ix_workflow_edges_workflow_id'), table_name='workflow_edges')
    op.drop_index('ix_workflow_edges_source_target', table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index(op.f('ix_tool_invocations_tool'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_status'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_execution_id'), table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_exec_tool', table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_agent_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_execution_states_status'), table_name='execution_states')
    op.drop_index('ix_execution_states_state', table_name='execution_states', postgresql_using='gin')
    op.drop_table('execution_states')
    op.drop_index(op.f('ix_execution_events_type'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_trace_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_severity'), table_name='execution_events')
    op.drop_index('ix_execution_events_payload', table_name='execution_events', postgresql_using='gin')
    op.drop_index(op.f('ix_execution_events_node_id'), table_name='execution_events')
    op.drop_index('ix_execution_events_execution_sequence', table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_execution_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_agent_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_evidence_chunks_execution_id'), table_name='evidence_chunks')
    op.drop_index(op.f('ix_evidence_chunks_content_hash'), table_name='evidence_chunks')
    op.drop_table('evidence_chunks')
    op.drop_index(op.f('ix_checkpoints_reason'), table_name='checkpoints')
    op.drop_index('ix_checkpoints_hash', table_name='checkpoints')
    op.drop_index('ix_checkpoints_execution_sequence', table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_execution_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index('ix_approvals_pending', table_name='approvals')
    op.drop_index(op.f('ix_approvals_expires_at'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_execution_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_invocations_status'), table_name='agent_invocations')
    op.drop_index(op.f('ix_agent_invocations_model_key'), table_name='agent_invocations')
    op.drop_index(op.f('ix_agent_invocations_execution_id'), table_name='agent_invocations')
    op.drop_index('ix_agent_invocations_exec_node', table_name='agent_invocations')
    op.drop_index(op.f('ix_agent_invocations_agent_id'), table_name='agent_invocations')
    op.drop_table('agent_invocations')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_tools_risk'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_trace_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index('ix_executions_resumable', table_name='executions', postgresql_where=None)
    op.drop_index(op.f('ix_executions_created_at'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_benchmark_runs_git_sha'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_agents_kind'), table_name='agents')
    op.drop_index(op.f('ix_agents_enabled'), table_name='agents')
    op.drop_index('ix_agents_definition', table_name='agents', postgresql_using='gin')
    op.drop_table('agents')
    # ### end Alembic commands ###
