"""add routing_settings table

Revision ID: 3d76760a1cdb
Revises: 575336924605
Create Date: 2026-09-03 16:21:40.844713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d76760a1cdb'
down_revision: Union[str, Sequence[str], None] = '575336924605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_settings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('active_provider', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_settings')
    # ### end Alembic commands ###
